name: build

trigger:
  tags:
    include: ["v*"]
pr: none

pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: redis
    image: redis
    ports:
      - 6379:6379
  - container: elasticsearch
    image: cccs/elasticsearch:7.6.0
    env:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISCOVERY_TYPE: 'single-node'
    ports:
      - 9200:9200

stages:
- stage: build
  jobs:
  - job: build_package
    displayName: Build Package
    steps:
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs: {versionSpec: 3.8}
    - script: |
        export VERSION=${BUILD_SOURCEBRANCH#"refs/tags/v"}
        echo $VERSION > assemblyline_core/VERSION
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U wheel cython pip
        python setup.py sdist
    - publish: $(System.DefaultWorkingDirectory)/dist/
      artifact: dist
    - publish: $(System.DefaultWorkingDirectory)/pipelines/
      artifact: pipelines
    - publish: $(System.DefaultWorkingDirectory)/test/
      artifact: test
- stage: test
  jobs:
  - job: run_test
    strategy:
      matrix:
        python3_7:
          python.version: '3.7'
        Python3_8:
          python.version: '3.8'
    timeoutInMinutes: 10
    services:
      elasticsearch: elasticsearch
      redis: redis
    steps:
    - checkout: none
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs:
        versionSpec: '$(python.version)'
    - download: current
      artifact: dist
    - download: current
      artifact: pipelines
    - download: current
      artifact: test
    - script: |
        set -x  # Echo commands before they are run
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev
        export VERSION=${BUILD_SOURCEBRANCH#"refs/tags/v"}
        sudo -E env "PATH=$PATH" python -m pip install --no-cache-dir -f $(Pipeline.Workspace)/dist/ "assemblyline-core[test]==${VERSION}"
        sudo mkdir -p /etc/assemblyline/
        sudo mkdir -p /var/cache/assemblyline/
        sudo chmod a+rw /var/cache/assemblyline/
        sudo cp $(Pipeline.Workspace)/pipelines/config.yml /etc/assemblyline
      displayName: Install package
    - script: pytest -rsx -vv
      workingDirectory: $(Pipeline.Workspace)/test
      displayName: Test
- stage: deploy
  jobs:
  - job: deploy
    displayName: Deploy packages and containers
    variables:
      - group: deployment-information
    steps:
    - download: current
      artifact: dist
      # Make sure a usable version of python is used for the deployment
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs:
        versionSpec: '3.8'
    - script: |
        set -xv  # Echo commands before they are run
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir twine
        ls dist
        twine upload --skip-existing --repository-url $TEST_REPOSITORY_URL dist/*
      workingDirectory: $(Pipeline.Workspace)
      displayName: Deploy to Test PyPI
      env:
        TWINE_USERNAME: $(twineUsername)
        TWINE_PASSWORD: $(twinePassword)
    - script: |
        set -xv  # Echo commands before they are run
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir twine
        ls dist
        twine upload --skip-existing dist/*
      workingDirectory: $(Pipeline.Workspace)
      displayName: Deploy to PyPI
      env:
        TWINE_USERNAME: $(twineUsername)
        TWINE_PASSWORD: $(twinePassword)
    - task: Docker@2
      displayName: Login to docker hub
      inputs:
        command: login
        containerRegistry: dockerhub
    - script: |
        set -xv  # Echo commands before they are run
        export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
        until sudo env "PATH=$PATH" python -m pip download "assemblyline-core==$TAG" --pre --no-deps &> /dev/null; do sleep 2; done
        docker build --build-arg version=$TAG -t cccs/assemblyline-core:$TAG -t cccs/assemblyline-core:latest deployment
        docker push cccs/assemblyline-core
      displayName: Deploy to Docker Hub
