name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-latest"

variables:
  # Try to checkout the matching branch, if the command fails, don't care.
  BRANCH_NAME: $[coalesce(variables['System.PullRequest.SourceBranch'], variables['System.PullRequest.TargetBranch'], replace(variables['Build.SourceBranch'], 'refs/heads/', ''))]

resources:
  repositories:
    - repository: assemblyline-base
      type: github
      endpoint: github-repo-sa
      name: CybercentreCanada/assemblyline-base

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_11:
          python.version: "3.11"
        Python3_12:
          python.version: "3.12"
        Python3_13:
          python.version: "3.13"
        Python3_14:
          python.version: "3.14"
    timeoutInMinutes: 10
    steps:
      - checkout: self
      - checkout: assemblyline-base

      - script: |
          # Checkout the branch corresponding to the pull request or the current branch
          set -xv
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
          git status
        displayName: Checkout branch
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-base

      - script: |
          # Start all services except pytest
          docker compose up -d --wait $(docker compose config --services | grep -v pytest)
        displayName: Setup environment
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-core/test

      - script: |
          # Start up pytest service from Docker Compose and run the tests
          docker compose run --build pytest pytest --durations=10 -rsx -vv --color=yes --junitxml=/opt/alv4/assemblyline-core/test/test-results.xml
        displayName: Test
        workingDirectory: $(System.DefaultWorkingDirectory)/assemblyline-core/test

      - task: PublishTestResults@2
        condition: always()
        displayName: Publish test results
        inputs:
          testResultsFiles: "assemblyline-core/test/test-results.xml"
          searchFolder: $(System.DefaultWorkingDirectory)
          testRunTitle: "python$(PYTHON_VERSION)"
