name: tests

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: 'ubuntu-18.04'

resources:
  containers:
  - container: redis
    image: redis
    ports:
      - 6379:6379
  - container: elasticsearch
    image: cccs/elasticsearch:7.8.0
    env:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      DISCOVERY_TYPE: 'single-node'
    ports:
      - 9200:9200
  repositories:
  - repository: assemblyline-base
    type: github
    endpoint: github
    name: CybercentreCanada/assemblyline-base

jobs:
- job: run_test
  strategy:
    matrix:
      python3_7:
        python.version: '3.7'
      Python3_8:
        python.version: '3.8'
      Python3_9:
        python.version: '3.9'

  timeoutInMinutes: 10
  services:
    elasticsearch: elasticsearch
    redis: redis

  steps:
    - task: UsePythonVersion@0
      displayName: Set python version
      inputs:
        versionSpec: '$(python.version)'
    - checkout: self
    - checkout: assemblyline-base
    - script: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev libfuzzy-dev python3-dev git
        sudo mkdir -p /etc/assemblyline/
        sudo mkdir -p /var/cache/assemblyline/
        sudo cp pipelines/config.yml /etc/assemblyline
        sudo chmod a+rw /var/cache/assemblyline/
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -U pip cython setuptools
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
      displayName: Setup Environment
    - script: |
        set -xv
        # Pull the target branch if this is a pull request, this way if there is no
        # matching branch in base for this core branch, we will end up on the target
        if [[ ! -z "${SYSTEM_PULLREQUEST_TARGETBRANCH}" ]]; then
          export BRANCH_NAME=${SYSTEM_PULLREQUEST_TARGETBRANCH}
          git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
        fi

        # Try to find the matching branch, first check for pull requst data, then fall back to build data
        # The parsed name isn't available in the pull request data, so use basename to parse it out
        export BRANCH_NAME=$(basename -- "$SYSTEM_PULLREQUEST_SOURCEBRANCH")
        export BRANCH_NAME=${BRANCH_NAME:-"$BUILD_SOURCEBRANCHNAME"}
        # Try to checkout the matching branch, if the command fails, don't care.
        git checkout -b $BRANCH_NAME -t origin/$BRANCH_NAME || true
        git status
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e .
      displayName: Install assemblyline
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-base
    - script: |
        sudo env "PATH=$PATH" python -m pip install --no-cache-dir -e .[test]
      displayName: Install assemblyline_core
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
    - script: sudo env "PATH=$PATH" python -m pytest -x -rsx -vv --cov=assemblyline_core --cov=$(Pipeline.Workspace)/s/assemblyline-base/assemblyline --cov-report=xml
      displayName: Test
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
    - script: python -m codecov
      displayName: Upload Coverage
      workingDirectory: $(Pipeline.Workspace)/s/assemblyline-core
      env:
        CODECOV_TOKEN: $(CODECOV_TOKEN)